#!/bin/sh /etc/rc.common
# Copyright (C) 2026 dreamboxone
# SPDX-License-Identifier: GPL-3.0-only
START=99
STOP=10
USE_PROCD=1
stop_service() {
 /usr/libexec/makhzan-download stop-workers
}
start_service() {
 procd_open_instance
 procd_set_param command /usr/libexec/makhzan-download daemon
 procd_set_param respawn 3600 5 5
 procd_set_param term_timeout 10
 procd_close_instance
}
